# ~/.config/starship.toml
palette = "catppuccin_mocha"

format = """
[](#89b4fa)\
$os\
$username\
[](bg:#f5c2e7 fg:#89b4fa)\
$directory\
[](fg:#f5c2e7 bg:#f9e2af)\
$git_branch\
$git_status\
[](fg:#f9e2af bg:#94e2d5)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#94e2d5 bg:#89dceb)\
$time\
[ ](fg:#89dceb)\
\n$character"""

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
overlay2 = "#9399b2"
surface2 = "#585b70"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:#89b4fa fg:#1e1e2e"

[username]
show_always = true
style_user = "bg:#89b4fa fg:#1e1e2e"
style_root = "bg:#89b4fa fg:#1e1e2e"
format = '[ $user ]($style)'

[directory]
style = "bg:#f5c2e7 fg:#1e1e2e"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
style = "bg:#f9e2af fg:#1e1e2e"
format = '[ $symbol $branch ]($style)'

[time]
disabled = false
time_format = "%I:%M %p"
style = "bg:#89dceb fg:#1e1e2e"
format = '[ $time ]($style)'
