# Minimal config for speed
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nodejs\
$php\
$python\
$ruby\
$rust\
$time\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[nodejs]
format = "[$symbol($version )]($style)"
detect_extensions = ["js", "mjs", "cjs", "ts", "tsx"]

[time]
disabled = false
format = '[$time]($style) '
time_format = "%I:%M %p"
style = "dimmed white"
